export const settings = {
  margin: 20,
  padding: 20,
  wordPadding: 10,
  height: 50,
  wordColor: 'black',
  glossColor: '#0ea5e9',
  titleColor: '#f87171',
  discourseUnitColor: '#fb923c',
  descriptionColor: '#65a30d',
  lineStrokeWidth: 2,
  fontSize: 14,
  fontFamily: '"trebuchet ms",verdana,arial,sans-serif',
  minWidth: 1024,
};
